CREATE USER sqlReader FROM LOGIN sqlReader
CREATE USER sqlWriter FROM LOGIN sqlWriter
CREATE USER sqlManager FROM LOGIN sqlManager

CREATE FULLTEXT CATALOG SearchCatalog WITH ACCENT_SENSITIVITY=OFF;

CREATE FULLTEXT STOPLIST SearchStoplist FROM SYSTEM STOPLIST;
-- Ignore very common words
ALTER FULLTEXT STOPLIST SearchStoplist ADD '€' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '€' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '£' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '£' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '¥' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '¥' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '¼' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '¼' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '½' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '½' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '¾' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '¾' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'ÿ' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'ÿ' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '00' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '00' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '01' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '01' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '02' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '02' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '03' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '03' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '04' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '04' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '05' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '05' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '06' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '06' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '07' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '07' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '08' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '08' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '09' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '09' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '10' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '10' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '100' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '100' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '11' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '11' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '12' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '12' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '13' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '13' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '14' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '14' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '15' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '15' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '16' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '16' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '17' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '17' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '18' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '18' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '19' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '19' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '20' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '20' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '2012' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '2012' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '2013' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '2013' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '2014' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '2014' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '2015' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '2015' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '2016' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '2016' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '2017' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '2017' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '2018' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '2018' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '2019' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '2019' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '21' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '21' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '22' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '22' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '23' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '23' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '24' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '24' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '25' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '25' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '26' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '26' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '27' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '27' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '28' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '28' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '29' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '29' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD '30' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD '30' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'active' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'active' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'best' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'best' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'bitcoin' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'bitcoin' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'board' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'board' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'code' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'code' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'com' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'com' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'contact' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'contact' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'content' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'content' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'cookies' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'cookies' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'copyright' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'copyright' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'dark' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'dark' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'de' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'de' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'delete' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'delete' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'don''t' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'don''t' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'email' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'email' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'en' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'en' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'english' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'english' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'faq' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'faq' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'form' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'form' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'forum' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'forum' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'help' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'help' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'home' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'home' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'http' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'http' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'inc' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'inc' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'index' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'index' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'info' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'info' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'la' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'la' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'last' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'last' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'links' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'links' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'list' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'list' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'log' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'log' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'login' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'login' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'may' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'may' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'net' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'net' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'new' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'new' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'news' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'news' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'not' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'not' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'one' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'one' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'onion' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'onion' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'online' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'online' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'page' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'page' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'password' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'password' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'please' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'please' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'post' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'post' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'posts' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'posts' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'powered' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'powered' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'privacy' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'privacy' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'read' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'read' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'register' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'register' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'registered' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'registered' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'remember' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'remember' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'report' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'report' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'rules' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'rules' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'search' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'search' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'service' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'service' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'site' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'site' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'software' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'software' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'sort' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'sort' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'support' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'support' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'tags' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'tags' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'team' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'team' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'time' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'time' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'times' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'times' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'tor' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'tor' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'us' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'us' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'user' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'user' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'users' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'users' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'using' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'using' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'utc' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'utc' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'version' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'version' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'view' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'view' LANGUAGE 'Neutral';
ALTER FULLTEXT STOPLIST SearchStoplist ADD 'web' LANGUAGE 1033;ALTER FULLTEXT STOPLIST SearchStoplist ADD 'web' LANGUAGE 'Neutral';
-- ban ped (list not commited for not helping giving keywords...)
GO
GRANT VIEW DEFINITION ON FULLTEXT STOPLIST :: SearchStoplist TO sqlReader; -- For retreive STOPWORDS
GO

CREATE TABLE Pages
(
	HiddenService NVARCHAR(37) NOT NULL,
	Url NVARCHAR(450) NOT NULL,
	Title NVARCHAR(450),
	Heading NVARCHAR(450),
	InnerText NVARCHAR(MAX),
	FirstCrawle DATETIME2(2) NOT NULL,
	LastCrawle DATETIME2(2) NOT NULL,
	CrawleError SMALLINT,
	Rank FLOAT NOT NULL DEFAULT 0.2,
	RankDate DATETIME2(2)
)
ALTER TABLE Pages ADD CONSTRAINT PK_Pages PRIMARY KEY CLUSTERED (Url)
CREATE NONCLUSTERED INDEX IX_Pages ON Pages (HiddenService)
GO
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Pages TO sqlWriter -- require for the MERGE and direct DELETE
GO

CREATE FULLTEXT INDEX ON Pages  
(   
	Title Language 1033,
	Heading Language 1033,
	InnerText Language 1033
)   
KEY INDEX PK_Pages ON SearchCatalog
WITH STOPLIST = SearchStoplist, CHANGE_TRACKING AUTO  
GO

CREATE TABLE BannedUrl
(
	UrlLike NVARCHAR(450) NOT NULL,
	Reason NVARCHAR(64) NULL,
	PagesPurge DATETIME2(2)
)
ALTER TABLE BannedUrl ADD CONSTRAINT PK_BannedUrl PRIMARY KEY CLUSTERED (UrlLike)
GO

CREATE TABLE BannedUrlQuery
(
	Query NVARCHAR(450) NOT NULL,
	Reason NVARCHAR(64) NULL,
	PagesPurge DATETIME2(2)
)
ALTER TABLE BannedUrlQuery ADD CONSTRAINT PK_BannedUrlQuery PRIMARY KEY CLUSTERED (UrlLike)
GO
GRANT SELECT ON BannedUrlQuery TO sqlWriter -- require for the MERGE
GO

CREATE TABLE HiddenServices
(
	HiddenService NVARCHAR(37) NOT NULL,
	IndexedPages INT,
	ReferredByHiddenServices INT,
	ReferredByPages INT,
	Rank FLOAT NOT NULL DEFAULT 0.2,
	RankDate DATETIME2(2)
)
ALTER TABLE HiddenServices ADD CONSTRAINT PK_HiddenServices PRIMARY KEY CLUSTERED (HiddenService)
GO

CREATE TABLE HiddenServiceMirrors
(
	HiddenService NVARCHAR(37) NOT NULL,
	HiddenServiceMain NVARCHAR(37) NOT NULL
)
ALTER TABLE HiddenServiceMirrors ADD CONSTRAINT PK_HiddenServiceMirrors PRIMARY KEY CLUSTERED (HiddenService) -- NO FK : HD may be new and not exist
GO

CREATE TABLE HiddenServiceLinks
(
	HiddenService NVARCHAR(37) NOT NULL,
	HiddenServiceTarget NVARCHAR(37) NOT NULL
)
ALTER TABLE HiddenServiceLinks ADD CONSTRAINT PK_HiddenServiceLinks PRIMARY KEY CLUSTERED (HiddenService,HiddenServiceTarget)  -- NO FK : HD may be new and not exist
-- NO PERF GAIN -- CREATE NONCLUSTERED INDEX IX_HiddenServiceLinks ON HiddenServiceLinks (HiddenServiceTarget)
GO
GRANT SELECT, INSERT, UPDATE ON HiddenServiceLinks TO sqlWriter -- require for the MERGE
GO

CREATE TABLE ContactMessages
(
	Date DATETIME2(2) NOT NULL,
	Message NVARCHAR(4000) NOT NULL
)
CREATE CLUSTERED INDEX IX_ContactMessages ON ContactMessages (Date)
GO
GRANT INSERT ON ContactMessages TO sqlReader -- new user messave
GO


CREATE TABLE CrawleRequest
(
	Url NVARCHAR(450) NOT NULL,
	Priority TINYINT NOT NULL,
	ExpireDate DATETIME2(2) NOT NULL
)
ALTER TABLE CrawleRequest ADD CONSTRAINT PK_CrawleRequest PRIMARY KEY CLUSTERED (Url)
CREATE NONCLUSTERED INDEX IX_CrawleRequest ON CrawleRequest (Priority,ExpireDate)
GO
GRANT SELECT,INSERT,DELETE ON CrawleRequest TO sqlManager -- purge expired by jog SQL + rescan self hd
GO


CREATE TABLE DbRowStats (
	[Date] [datetime2](2) NOT NULL,
	[HiddenServices] [int] NOT NULL,
	[HiddenServicesOK] [int] NOT NULL,
	[Pages] [int] NOT NULL,
	[PagesOK] [int] NOT NULL
)
ALTER TABLE DbRowStats ADD CONSTRAINT PK_DbRowStats PRIMARY KEY CLUSTERED ([Date])
GO