CREATE USER sqlWriter FROM LOGIN sqlWriter
GRANT SELECT, INSERT, UPDATE, DELETE TO sqlWriter

IF OBJECT_ID('dbo.HistoPages') IS NOT NULL
	DROP TABLE HistoPages

CREATE TABLE HistoPages
(
	Url NVARCHAR(450) NOT NULL,
	HtmlRaw NVARCHAR(MAX)
)
ALTER TABLE HistoPages ADD CONSTRAINT PK_HistoPages PRIMARY KEY CLUSTERED (Url)
